# Generated by Django 5.0.3 on 2024-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_hash",
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
